import type { ClaudeSdkGolden } from "./capture/types.js";
import type { ClaudeProfileArtifactDescriptor } from "./types.js";

const PROFILE_NAMES: Readonly<Record<ClaudeProfileArtifactDescriptor["stem"], string>> = {
    "claude-fable-5": "Claude Fable 5",
    "claude-opus-4-8": "Claude Opus 4.8",
    "claude-sonnet-5": "Claude Sonnet 5",
};

const COMMON_PROMPT_CHANGES = [
    "Prepends Rig's identity before the captured Claude Code prompt so the model sees the active harness first.",
    "Removes Claude Code's file-backed memory instructions because Rig does not expose that memory runtime.",
    "Removes Claude Code product-surface and `/fast` guidance that does not apply inside Rig.",
] as const;

const SONNET_PROMPT_CHANGES = [
    "Removes session guidance that calls `Agent` with Claude Code-only `subagent_type` values.",
    "Removes Claude Code help and feedback instructions.",
    "Renames durable repository guidance from `CLAUDE.md` to Rig's `AGENTS.md` convention.",
] as const;

export function createClaudeProfileSummary(options: {
    target: ClaudeProfileArtifactDescriptor;
    golden: ClaudeSdkGolden;
    promptPatch: string;
    toolsPatch: string;
}): string {
    const { target, golden, promptPatch, toolsPatch } = options;
    const title = PROFILE_NAMES[target.stem];
    const promptChanges =
        target.stem === "claude-sonnet-5"
            ? [...COMMON_PROMPT_CHANGES, ...SONNET_PROMPT_CHANGES]
            : COMMON_PROMPT_CHANGES;
    const promptChangeLines = promptChanges.map((change) => `- ${change}`);
    const markdownPromptPatch = promptPatch.replace(/[ \t]+$/gmu, (whitespace) =>
        whitespace.replaceAll(" ", "·").replaceAll("\t", "→"),
    );
    const markdownToolsPatch = toolsPatch.replace(/[ \t]+$/gmu, (whitespace) =>
        whitespace.replaceAll(" ", "·").replaceAll("\t", "→"),
    );

    return [
        `# ${title} profile`,
        "",
        "> This document is generated by `captureClaudeSdkGoldens.ts`. It summarizes the intentional Rig deviations and embeds the complete persisted diffs for GitHub review.",
        "",
        "## Source",
        "",
        `- Profile: [${target.stem}.ts](./${target.stem}.ts)`,
        `- Captured through \`${golden.source.sdkPackage}\` ${golden.source.sdkVersion}, bundling Claude Code ${golden.source.claudeCodeVersion}`,
        `- Claude Code commit: \`${golden.source.commit}\``,
        `- Requested model: \`${golden.source.modelOption}\`; captured wire model: \`${golden.wireModel}\``,
        `- Capture metadata: [${target.stem}.capture.json](./claude/${target.stem}.capture.json)`,
        "",
        "## Prompt changes",
        "",
        ...promptChangeLines,
        "",
        `The untouched capture is [${target.stem}.golden.md](./claude/${target.stem}.golden.md), the prompt Rig sends is [${target.stem}.md](./claude/${target.stem}.md), and the standalone diff is [${target.stem}.patch](./claude/${target.stem}.patch).`,
        "",
        "## Tool changes",
        "",
        "Official tool definitions are retained exactly where Rig implements the same behavior. The following differences are intentional:",
        "",
        "- Removed unsupported Claude Code tools: `CronCreate`, `CronDelete`, `CronList`, `EnterWorktree`, `ExitWorktree`, `NotebookEdit`, `ReportFindings`, `ScheduleWakeup`, and `Skill`.",
        "- Added Rig tools: `Glob`, `Grep`, `AskUserQuestion`, and `WaitForWorkflow`.",
        "",
        "| Tool | Rig deviation |",
        "| --- | --- |",
        "| `Agent` | Uses Rig's resumable subagent contract; removes `subagent_type` and `isolation`, and adds `context`, `effort`, and `provider`. |",
        "| `Bash` | Adds secret-bundle injection, uses Rig's reviewed sandbox escalation, removes Claude Code attribution text, and describes Rig's non-persistent shell state. |",
        "| `Read` | Removes `pages` and claims for unsupported PDF rendering and notebook-cell parsing. |",
        "| `TaskCreate` | Removes the unsupported Plan-mode instruction. |",
        "| `TaskList` | Removes the unsupported task-comments claim. |",
        "| `TaskOutput` | Describes Rig background shell and workflow results. |",
        "| `TaskStop` | Uses Rig task IDs, removes `shell_id`, and requires `task_id`. |",
        "| `WebFetch` | Drops the model-only JSON Schema `uri` format annotation; execution still validates URLs. |",
        "| `Workflow` | Uses Rig's Python workflow contract and requires exactly one of `script` or `scriptPath`. |",
        "| `SendMessage` | Targets resumable Rig subagents and adds summary and effort fields. |",
        "",
        `The official definitions are [${target.stem}.tools.golden.json](./claude/${target.stem}.tools.golden.json), Rig's definitions are [${target.stem}.tools.json](./claude/${target.stem}.tools.json), and the standalone diff is [${target.stem}.tools.patch](./claude/${target.stem}.tools.patch).`,
        "",
        "## Full prompt diff",
        "",
        "The embedded diffs render trailing spaces as `·` and trailing tabs as `→`; the linked `.patch` files retain the exact captured bytes.",
        "",
        "````diff",
        markdownPromptPatch.trimEnd(),
        "````",
        "",
        "## Full tool diff",
        "",
        "````diff",
        markdownToolsPatch.trimEnd(),
        "````",
        "",
    ].join("\n");
}
